
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: windows-latest

    steps:
    - name: 'Log into Azure using github secret AZURE_CREDENTIALS'
      uses: Azure/login@v1.6.1


    
